package com.example.dynamicmeta;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.boot.test.context.runner.WebApplicationContextRunner;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class SchemaDiscoveryServiceTests {

    @Test
    void discoversTheContainingApplicationsDataSource() throws Exception {
        JdbcDataSource dataSource = dataSource("host");
        createSchema(dataSource);
        SchemaDiscoveryService service = new SchemaDiscoveryService(
                dataSource, new SchemaToEntityProperties());

        Map<String, Object> result = service.discover("PUBLIC", List.of());

        assertThat(result).containsEntry("dialect", "h2").containsEntry("schema", "PUBLIC");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> tables = (List<Map<String, Object>>) result.get("tables");
        assertThat(tables).extracting(table -> table.get("name")).contains("CUSTOMERS", "ORDERS");
        Map<String, Object> orders = tables.stream()
                .filter(table -> "ORDERS".equals(table.get("name")))
                .findFirst().orElseThrow();
        assertThat((List<?>) orders.get("foreignKeys")).hasSize(1);
        assertThat(orders.get("primaryKey")).isEqualTo("ID");
    }

    @Test
    void supportsAnExplicitJdbcUrlWithoutReplacingTheHostDataSource() throws Exception {
        JdbcDataSource host = dataSource("host2");
        JdbcDataSource external = dataSource("external");
        createSchema(external);
        SchemaDiscoveryService service = new SchemaDiscoveryService(host, new SchemaToEntityProperties());

        Map<String, Object> result = service.discover(new SchemaDiscoveryService.ConnectionRequest(
                "jdbc:h2:mem:external;DB_CLOSE_DELAY=-1", "sa", "", "PUBLIC",
                List.of("CUSTOMERS"), null, null));

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> tables = (List<Map<String, Object>>) result.get("tables");
        assertThat(tables).extracting(table -> table.get("name")).containsExactly("CUSTOMERS");
    }

    @Test
    void autoConfiguresWhenADataSourceIsPresentAndCanBeDisabled() {
        ApplicationContextRunner runner = new ApplicationContextRunner()
                .withConfiguration(AutoConfigurations.of(SchemaToEntityAutoConfiguration.class))
                .withBean(DataSource.class, () -> dataSource("autoconfig"));

        runner.run(context -> assertThat(context).hasSingleBean(SchemaDiscoveryService.class));
        runner.withPropertyValues("schema-to-entity.enabled=false")
                .run(context -> assertThat(context).doesNotHaveBean(SchemaDiscoveryService.class));
    }

    @Test
    void contributesTheControllerToServletApplications() {
        new WebApplicationContextRunner()
                .withConfiguration(AutoConfigurations.of(SchemaToEntityAutoConfiguration.class))
                .withBean(DataSource.class, () -> dataSource("web"))
                .run(context -> {
                    assertThat(context).hasSingleBean(SchemaDiscoveryService.class);
                    assertThat(context).hasSingleBean(SchemaDiscoveryController.class);
                });
    }

    private static JdbcDataSource dataSource(String database) {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:" + database + ";DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    private static void createSchema(DataSource dataSource) throws Exception {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("create table customers (id bigint generated by default as identity primary key, name varchar(80) not null)");
            statement.execute("create table orders (id bigint primary key, customer_id bigint not null, constraint fk_customer foreign key (customer_id) references customers(id))");
        }
    }
}
